package com.mokah.veterinary.security.enums;

public enum Permits {

    VIEW_USERS,
    DELETE_USERS,
    VIEW_OWNERS,
    CREATE_OWNERS,
    UPDATE_OWNERS,


    VIEW_PETS,
    CREATE_PETS,
    UPDATE_PETS,
    DELETE_PETS,


    VIEW_APPOINTMENTS,
    CREATE_APPOINTMENTS,
    UPDATE_APPOINTMENTS,
    DELETE_APPOINTMENTS,
    VIEW_BRANCHES,
    MANAGE_BRANCHES,


    VIEW_DIAGNOSES,
    CREATE_DIAGNOSES,
    UPDATE_DIAGNOSES,
    DELETE_DIAGNOSES,
    VIEW_PRESCRIPTIONS,
    CREATE_PRESCRIPTIONS,
    VIEW_CLINICAL_RECORDS,
    CREATE_CLINICAL_RECORDS,
    UPDATE_CLINICAL_RECORDS,
    VIEW_MEDICATIONS,
    MANAGE_MEDICATIONS
}
