package com.mokah.veterinary.security.enums;

public enum Permits {
    VIEW_USERS,
    CREATE_USERS,
    UPDATE_USERS,
    DELETE_USERS,

    VIEW_PETS,
    CREATE_PETS,
    UPDATE_PETS,
    DELETE_PETS,

    VIEW_APPOINTMENTS,
    CREATE_APPOINTMENTS,
    UPDATE_APPOINTMENTS,
    DELETE_APPOINTMENTS,

    VIEW_DIAGNOSES,
    CREATE_DIAGNOSES,
    UPDATE_DIAGNOSES,
    DELETE_DIAGNOSES,

    VIEW_PRESCRIPTIONS,
    CREATE_PRESCRIPTIONS,
    UPDATE_PRESCRIPTIONS,
    DELETE_PRESCRIPTIONS
}
